config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show]
  resources :photos do
    resources :ratings, only: [:create]
  end

  root 'photos#index'
  resource :session, only: [:new, :create, :destroy]

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  has_many :ratings, dependent: :destroy
  validates :url, presence: true, uniqueness: true

  def avg
    self.ratings.average(:value)
  end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo, touch: true
  validates_inclusion_of :value, :in => 1..10
  validates :user_id, uniqueness: {scope: :photo_id}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :ratings
  has_many :photos
  has_many :given_ratings, through: :photos, source: :ratings
  validates :username, :email, {presence: true, uniqueness: true}
  # validates :password, length: {minimum: 20}

  def overall_avg
    self.given_ratings.average(:value)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  before_filter :ensure_login, only: [:new, :edit, :destroy]
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  private
  def ensure_login
    redirect_to root_path unless logged_in?
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all.order(created_at: :desc)
  end

  def show
    @photo = Photo.find(params[:id])
    @average = @photo.avg
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user = current_user
    if @photo.save
      redirect_to @photo
    else
      render :new
    end
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update(photo_params)
      redirect_to @photo
    else
      render :edit
    end
  end

  def destroy
    photo = Photo.find(params[:id])
    photo.destroy
    redirect_to root_path
  end

  private
  def photo_params
    params.require(:photo).permit(:title, :url)
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def create
    rating = Rating.new(photo_id: params[:photo_id], value: params[:rating][:value])
    rating.user = current_user
    rating.save
    redirect_to :back
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
skip_before_action :ensure_login, only: :new
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to new_session_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_login, only: :new

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.authenticate(params[:user][:password_confirmation]) && @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @average = @user.overall_avg
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :hometown, :bio, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RateMySquirrel</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1><%= link_to 'RATE MY SQUIRREL', root_path %></h1>
    <span id="authentication_bar">
      <% if logged_in? %>
      <p>Welcome, <%= current_user.username %> | <%= link_to 'Log out', '/session', method: :delete %></p>
      <% else %>
      <p><a href="/session/new">Log in</a> | <a href="/users/new">Register</a></p>
      <% end %>
    </span>
  </header>
<%= yield %>
</body>
</html>

app/views/photos/_form.html.erb
<%= form_for @photo do |f| %>
  <ul class="form_list">
    <li>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </li>
    <li>
      <%= f.label :url %>
      <%= f.text_field :url %>
    </li>
    <li>
      <%= f.submit 'Save' %>
    </li>
  </ul>
<% end %>

app/views/photos/_photo.html.erb
<div class="index_link"><%= link_to photo.title, photo %></div>
<div class="index_thumbnail"><%= image_tag photo.url, height: '100' %></div>

app/views/photos/edit.html.erb
<%= render 'form' %>

app/views/photos/index.html.erb
<div id="new_photo_button"><%= link_to 'New Photo', new_photo_path %></div>
<%= render @photos %>

app/views/photos/new.html.erb
<%= render 'form' %>

app/views/photos/show.html.erb
<div id="photo_banner">
    <h2><%= @photo.title %></h2>
    <%= link_to @photo.user.username, user_path(@photo.user), id:"photo_user_link" %>
</div>
<%= image_tag @photo.url %>
<% if logged_in? && current_user == @photo.user %>
  <%= link_to 'Edit photo', edit_photo_path, class: "admin_command" %>
  <%= link_to 'Delete photo', "/photos/#{@photo.id}", method: :delete, class: "admin_command" %>
<% end %>
<fieldset><legend>Rate this squirrel</legend>
  <%= form_for [@photo, @photo.ratings.new] do |f| %>
  <% counter = 1 %>
      <% while counter <= 10 %>
        <%= f.label "#{counter}" %>
        <%= f.radio_button :value, counter %>
        <% counter += 1 %>
      <% end %>
        <%= f.submit 'Rate' %>
  <% end %>
  <span id="ratings_box">Average rating: <%= @average %></span>
</fieldset>

app/views/users/new.html.erb
<fieldset>
  <legend>Register</legend>
  <%= form_for @user do |f| %>
  <ul class="form_list">
    <li>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </li>
    <li>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </li>
    <li>
      <%= f.label :hometown %>
      <%= f.text_field :hometown %>
    </li>
    <li>
      <%= f.label :bio %>
      <%= f.text_area :bio %>
    </li>
    <li>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </li>
    <li>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </li>
    <li>
      <%= f.submit 'Register' %>
    </li>
  </ul>
  <% end %>
</fieldset>

app/views/users/show.html.erb
<fieldset>
  <legend><h2><%= @user.username %></h2></legend>
  <div>
    <p class="profile_header">Hometown:</p>
    <p><%= @user.hometown %></p>
  </div>
  <div>
    <p class="profile_header">Bio:</p>
    <p><%= @user.bio %></p>
  </div>
  <div>
    <p class="profile_header">Average rating of <%= @user.username %>'s photos:</p>
    <p><%= @average %></p>
  </div>
</fieldset>